#!/usr/bin/env bash

set -e

GIT_SHA="$(git rev-parse HEAD | cut -c 1-8)"

function build_lambda_layer {
  IMAGE="globalforestwatch/${1}_layer"

  echo "BUILD image ${IMAGE}"
  docker build -t "${IMAGE}":"${GIT_SHA}" -f docker/"${1}"/Dockerfile .

  echo "CREATE container"
  docker run --name lambda_layer -itd "${IMAGE}":"${GIT_SHA}" /bin/bash

  echo "COPY ZIP package to host"
  docker cp lambda_layer:/var/task/layer.zip docker/"${1}"/layer.zip

  echo "REMOVE container"
  docker rm -f lambda_layer
}

# Download the dependency lambda layers
RUNTIME_PREFIX="python3.13"
MERCANTILE_VERSION_SUFFIX="1.2.1"
NUMPY_VERSION_SUFFIX="2.4.2"
PANDAS_VERSION_SUFFIX="2.3.3"
PILLOW_VERSION_SUFFIX="12.1.0"
RASTERIO_VERSION_SUFFIX="1.4.4"
SHAPELY_VERSION_SUFFIX="2.1.2"

MERCANTILE_FILENAME="${RUNTIME_PREFIX}-mercantile_${MERCANTILE_VERSION_SUFFIX}.zip"
NUMPY_FILENAME="${RUNTIME_PREFIX}-numpy_${NUMPY_VERSION_SUFFIX}.zip"
PANDAS_FILENAME="${RUNTIME_PREFIX}-pandas_${NUMPY_VERSION_SUFFIX}.zip"
PILLOW_FILENAME="${RUNTIME_PREFIX}-pillow_${PILLOW_VERSION_SUFFIX}.zip"
RASTERIO_FILENAME="${RUNTIME_PREFIX}-rasterio_${RASTERIO_VERSION_SUFFIX}.zip"
SHAPELY_FILENAME="${RUNTIME_PREFIX}-shapely_${SHAPELY_VERSION_SUFFIX}.zip"

mkdir -p docker/layers

for filename in $MERCANTILE_FILENAME $NUMPY_FILENAME $PILLOW_FILENAME $RASTERIO_FILENAME $SHAPELY_FILENAME; do
  if ! [ -f docker/layers/${filename} ]; then
      aws s3 cp s3://gfw-pipelines-dev/lambda_layers/${filename} docker/layers/${filename}
  fi
done

lambda_layers=( raster_analysis )

for l in "${lambda_layers[@]}"
do
    echo "Build lambda layer ${l}"
    build_lambda_layer "${l}"
done

docker build -t gfw-raster-analysis-test -f docker/test/Dockerfile .
