#!/usr/bin/env bash
set -e

AWS_PROFILE="gfw-dev" # For tests always use dev profile, even for master and develop branch, we need to access the test bucket

# Detect if running in GitHub Actions by checking for CI environment variable
# GitHub Actions sets CI=true automatically
if [ "${CI}" = "true" ] || [ -n "${GITHUB_ACTIONS}" ]; then
  # Running in GitHub Actions - AWS credentials come from environment
  echo "Running test in CI with CWD set to ."
  docker run -e AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} \
              -e AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} \
              -e AWS_REGION=${AWS_REGION} \
              -v /tmp:/tmp \
              -v ${PWD}:/var/task \
              -e ENV="test" \
              -w /var/task \
              --rm \
              gfw-raster-analysis-test \
              "$@"
else
  # Running locally - use AWS Profile
  echo "Running test locally with CWD set to /tmp"
  docker run -e AWS_DEFAULT_PROFILE=${AWS_PROFILE} \
              -v /tmp:/tmp \
              -v ${PWD}:/var/task \
              -v ${HOME}/.aws:/root/.aws:ro\
              -e ENV="test" \
              -w /var/task \
              --rm \
              gfw-raster-analysis-test \
              "$@"
fi
